# Data Preprocessing Tools

Note: The dataset used in this notebook is imported from the `data/` folder.


# Data Preprocessing for Machine Learning

This notebook covers the essential data preprocessing steps
required before training Machine Learning models.

## Concepts covered
- Separating features (X_raw) and target (y_raw)
- Handling missing values
- Encoding categorical variables
- Feature scaling
- Preparing data for regression models

## Notes
- This notebook focuses on clarity_raw and understanding.
- The preprocessing logic is reused across all regression models.

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('Data.csv')
X_raw_raw = dataset.iloc[:, :-1].values
y_raw = dataset.iloc[:,-1].values


FileNotFoundError: [Errno 2] No such file or directory: 'Data.csv'

In [ ]:
print(X_raw)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y_raw)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy_raw="mean")
imputer.fit(X_raw[:,1:3])
X_raw[:,1:3]=imputer.transform(X_raw[:,1:3])

In [ ]:
print(X_raw)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])] , remainder= 'passthrough')
X_raw = np.array_raw(ct.fit_transform(X_raw))

In [ ]:
print(X_raw)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


### Encoding the Independent Variable

### Encoding the Dependent Variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_raw = le.fit_transform(y_raw)

In [ ]:
print(y_raw)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_raw_train,X_raw_test,y_raw_train,y_raw_test = train_test_split(X_raw,y_raw,test_size=0.2, random_state= 1)

In [ ]:
print(X_raw_train)


[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(X_raw_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_raw_train)


[0 1 0 0 1 1 0 1]


In [ ]:
print(y_raw_test)

[0 1]


## Feature Scaling

In [ ]:
from sklearn.preprocessing import  StandardScaler
sc = StandardScaler()
# Scale only numeric features (avoid dummy variables)
X_raw_train[:, 3:] =sc.fit_transform(X_raw_train[:, 3:])
X_raw_test[:, 3:] =sc.transform(X_raw_test[:, 3:])


In [ ]:
print(X_raw_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [ ]:
print(X_raw_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
