# Support Vector Regression (SVR)

Note: The dataset used in this notebook is imported from the `data/` folder.


### Support Vector Regression (SVR)

Support Vector Regression is applied to handle non-linear data using kernel-based learning.  
The model is trained on scaled features, and predictions are inverse-transformed for real-world interpretation.


## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [6]:
dataset = pd.read_csv('Position_Salaries.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [7]:
#print(X)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [8]:
#print(y)

[  45000   50000   60000   80000  110000  150000  200000  300000  500000
 1000000]


In [9]:
y = y.reshape(len(y),1)

In [10]:
#print(y)

[[  45000]
 [  50000]
 [  60000]
 [  80000]
 [ 110000]
 [ 150000]
 [ 200000]
 [ 300000]
 [ 500000]
 [1000000]]


## Feature Scaling

In [11]:
from sklearn.preprocessing import  StandardScaler
sc_x = StandardScaler()
sc_y = StandardScaler()
X= sc_x.fit_transform(X)
y= sc_y.fit_transform(y)




In [18]:
print(X)
print()
print(y)

[[-1.5666989 ]
 [-1.21854359]
 [-0.87038828]
 [-0.52223297]
 [-0.17407766]
 [ 0.17407766]
 [ 0.52223297]
 [ 0.87038828]
 [ 1.21854359]
 [ 1.5666989 ]]

[[-0.72004253]
 [-0.70243757]
 [-0.66722767]
 [-0.59680786]
 [-0.49117815]
 [-0.35033854]
 [-0.17428902]
 [ 0.17781001]
 [ 0.88200808]
 [ 2.64250325]]


## Training the SVR model on the whole dataset

In [19]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X,y)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

## Predicting a new result

### Predicting a New Result

Two equivalent approaches can be used for prediction:

1. Step-by-step prediction using intermediate variables (clear and beginner-friendly).
2. Compact one-line prediction (concise and efficient).

Both methods produce the same result as long as scaling and inverse scaling are handled correctly.


In [28]:
raw_input = [[6.5]]
scaled_input = sc_x.transform(raw_input)
prediction = regressor.predict(scaled_input)
reshape_2d = prediction.reshape(-1,1)
real_salary = sc_y.inverse_transform(reshape_2d)
print(real_salary)

[[170370.0204065]]


In [27]:
#sc_y.inverse_transform(regressor.predict(sc_x.transform([[6.5]])).reshape(-1,1))

array([[170370.0204065]])

## Visualising the SVR results

In [2]:
plt.scatter(sc_x.inverse_transform(X),sc_y.inverse_transform(y),color = 'brown')
plt.plot(sc_x.inverse_transform(X),sc_y.inverse_transform(regressor.predict(X).reshape(-1,1)),color = 'gold')
plt.title('Truth or Bluff (SVR)')
plt.ticklabel_format(style='plain') # using for display exact numerical figure instaed of e
plt.xlabel("Position")
plt.ylabel("Salary")
plt.show()

NameError: name 'sc_x' is not defined

## Visualising the SVR results (for higher resolution and smoother curve)

In [ ]:
X_grid = np.arange(min(sc_X.inverse_transform(X)), max(sc_X.inverse_transform(X)), 0.1)
X_grid = X_grid.reshape((len(X_grid), 1))
plt.scatter(sc_X.inverse_transform(X), sc_y.inverse_transform(y), color = 'red')
plt.plot(X_grid, sc_y.inverse_transform(regressor.predict(sc_X.transform(X_grid)).reshape(-1,1)), color = 'blue')
plt.title('Truth or Bluff (SVR)')
plt.xlabel('Position level')
plt.ylabel('Salary')
plt.show()